config:
    application:
        name: "Simple web studio"
    window:
        startLocationX: 250
        startLocationY: 250
        width: 1920
        height: 1080
    images:
        icon: "classpath:images/favicon.ico"
    htmlTags: "h1,h2,h3,h4,h5,h6,b,em,ul,ol,a,nav,aside,header,section,div,html,body,script,link,meta,img,audio,iframe,form,input,table,td,tr"
